### ISSUE TITLE
importing hssm module 'numpy.__config__' has no attribute 'get_info'

### ISSUE THREAD

**Issue by Cumol** [lnccbrown/HSSM#280]
**Describe the bug**

When importing hssm after fresh install:

```
Traceback (most recent call last):
  File "/home/muad/anaconda3/envs/hssm9/lib/python3.9/site-packages/pytensor/configparser.py", line 201, in fetch_val_for_key
    return self._pytensor_cfg.get(section, option)
  File "/home/muad/anaconda3/envs/hssm9/lib/python3.9/configparser.py", line 781, in get
    d = self._unify_values(section, vars)
  File "/home/muad/anaconda3/envs/hssm9/lib/python3.9/configparser.py", line 1149, in _unify_values
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'blas'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/muad/anaconda3/envs/hssm9/lib/python3.9/site-packages/pytensor/configparser.py", line 317, in __get__
    val_str = cls.fetch_val_for_key(self.name, delete_key=delete_key)
  File "/home/muad/anaconda3/envs/hssm9/lib/python3.9/site-packages/pytensor/configparser.py", line 205, in fetch_val_for_key
    raise KeyError(key)
KeyError: 'blas__ldflags'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/muad/anaconda3/envs/hssm9/lib/python3.9/site-packages/hssm/__init__.py", line 7, in <module>
    from .config import ModelConfig
  File "/home/muad/anaconda3/envs/hssm9/lib/python3.9/site-packages/hssm/config.py", line 10, in <module>
    from .defaults import LogLik, LoglikKind, SupportedModels, default_model_config
  File "/home/muad/anaconda3/envs/hssm9/lib/python3.9/site-packages/hssm/defaults.py", line 5, in <module>
    import bambi as bmb
  File "/home/muad/anaconda3/envs/hssm9/lib/python3.9/site-packages/bambi/__init__.py", line 3, in <module>
    from pymc import math
  File "/home/muad/anaconda3/envs/hssm9/lib/python3.9/site-packages/pymc/__init__.py", line 47, in <module>
    __set_compiler_flags()
  File "/home/muad/anaconda3/envs/hssm9/lib/python3.9/site-packages/pymc/__init__.py", line 30, in __set_compiler_flags
    import pytensor
  File "/home/muad/anaconda3/envs/hssm9/lib/python3.9/site-packages/pytensor/__init__.py", line 119, in <module>
    from pytensor import scalar, tensor
  File "/home/muad/anaconda3/envs/hssm9/lib/python3.9/site-packages/pytensor/tensor/__init__.py", line 106, in <module>
    from pytensor.tensor import (  # noqa
  File "/home/muad/anaconda3/envs/hssm9/lib/python3.9/site-packages/pytensor/tensor/blas.py", line 102, in <module>
    from pytensor.tensor.blas_headers import blas_header_text, blas_header_version
  File "/home/muad/anaconda3/envs/hssm9/lib/python3.9/site-packages/pytensor/tensor/blas_headers.py", line 1015, in <module>
    if not config.blas__ldflags:
  File "/home/muad/anaconda3/envs/hssm9/lib/python3.9/site-packages/pytensor/configparser.py", line 321, in __get__
    val_str = self.default()
  File "/home/muad/anaconda3/envs/hssm9/lib/python3.9/site-packages/pytensor/link/c/cmodule.py", line 2720, in default_blas_ldflags
    blas_info = np.__config__.get_info("blas_opt")
AttributeError: module 'numpy.__config__' has no attribute 'get_info'
```

**HSSM version**
0.1.5

**To Reproduce**
Inside fresh python 3.9 environment (but same happens with 3.10 and 3.11)

`pip install hssm`

run `python`

`import hssm`

**Additional context**
Downgrading numpy to 1.23.4 resolves the issue

`pip install --upgrade numpy==1.23.4`

**Comment by digicosmos86** [comment]
Thank you for bringing this to our attention! It seems that numpy 1.26 was released on Sep 16 and there might be some compatibility issues with PyTensor. We'll contact the PyTensor team and hopefully they'll fix this soon. In the meantime, limiting the numpy version is the best temporary fix.

**Comment by digicosmos86** [comment]
There is already an issue in pytensor repo https://github.com/pymc-devs/pytensor/issues/441

**Comment by digicosmos86** [comment]
Seems this is fixed in PyMC 5.9.0. Closing

**Comment by dmd** [comment]
I am getting this even though I have PyMC 5.9.0:

```
File /cm/shared/anaconda3/envs/hssm/lib/python3.11/site-packages/pytensor/link/c/cmodule.py:2720, in default_blas_ldflags()
   2718 warn_record = []
   2719 try:
-> 2720     blas_info = np.__config__.get_info("blas_opt")
   2722     # If we are in a EPD installation, mkl is available
   2723     if "EPD" in sys.version:

AttributeError: module 'numpy.__config__' has no attribute 'get_info'

In [2]:
Do you really want to exit ([y]/n)?
Shutting down kernel
(hssm) $ conda list pymc
# packages in environment at /cm/shared/anaconda3/envs/hssm:
#
# Name                    Version                   Build  Channel
pymc                      5.9.0                    pypi_0    pypi
```

**Comment by dmd** [comment]
Could you tell me what the correct way to do the install is then? I did:

```
$ python3.11 -m venv venvs/hssm
$ . venvs/hssm/bin/activate
$ pip install hssm
$ python
>>> import hssm
```

and that fails. I would have expected a clean install, from scratch, in a brand new venv to work, and it doesn't.

**Comment by digicosmos86** [comment]
Sorry we are not aware that a clean install would fail. Something must have changed on some of our dependencies that the wrong numpy version gets installed.

To fix this, simply fix the numpy version after the initial installation of hssm:

```sh
pip install --upgrade numpy==1.23.4
```

It doesn't have to be 1.23.4. Any version before 1.26.0 should work

**Comment by dmd** [comment]
Thanks, that fixes it.
