### ISSUE TITLE
Error when using nuts_numpyro: "AttributeError: module 'jax.numpy' has no attribute 'product'"

### ISSUE THREAD

**Issue by igrahek** [lnccbrown/HSSM#293]
I'm getting the error below when I run a regression model with nuts_numpyro. I get the same error when I do pip install hssm and pip install git+https://github.com/lnccbrown/HSSM.git

```
Compiling...Traceback (most recent call last): 
File /oscar/data/ashenhav/igrahek/LFXC_Interval/Analysis/702/ddm/bash/../models/model1.py", line 62, in <module> modelObject = model.sample( ^^^^^^^^^^^^^ 
File "/users/igrahek/.conda/envs/pyHSSM/lib/python3.11/site-packages/hssm/hssm.py", line 343, in sample self._inference_obj = self.model.fit(inference_method=sampler, **kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ 
File "/users/igrahek/.conda/envs/pyHSSM/lib/python3.11/site-packages/bambi/models.py", line 325, in fit return self.backend.run( ^^^^^^^^^^^^^^^^^ File "/users/igrahek/.conda/envs/pyHSSM/lib/python3.11/site-packages/bambi/backend/pymc.py", line 96, in run result = self._run_mcmc( ^^^^^^^^^^^^^^^ 
File "/users/igrahek/.conda/envs/pyHSSM/lib/python3.11/site-packages/bambi/backend/pymc.py", line 211, in _run_mcmc idata = pymc.sampling_jax.sample_numpyro_nuts( ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ 
File "/users/igrahek/.conda/envs/pyHSSM/lib/python3.11/site-packages/pymc/sampling/jax.py", line 630, in sample_numpyro_nuts logp_fn = get_jaxified_logp(model, negative_logp=False) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ 
File "/users/igrahek/.conda/envs/pyHSSM/lib/python3.11/site-packages/pymc/sampling/jax.py", line 136, in get_jaxified_logp logp_fn = get_jaxified_graph(inputs=model.value_vars, outputs=[model_logp]) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ 
File "/users/igrahek/.conda/envs/pyHSSM/lib/python3.11/site-packages/pymc/sampling/jax.py", line 129, in get_jaxified_graph return jax_funcify(fgraph) ^^^^^^^^^^^^^^^^^^^ 
File "/users/igrahek/.conda/envs/pyHSSM/lib/python3.11/functools.py", line 909, in wrapper return dispatch(args[0].__class__)(*args, **kw) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ 
File "/users/igrahek/.conda/envs/pyHSSM/lib/python3.11/site-packages/pytensor/link/jax/dispatch/basic.py", line 51, in jax_funcify_FunctionGraph return fgraph_to_python( ^^^^^^^^^^^^^^^^^
 File "/users/igrahek/.conda/envs/pyHSSM/lib/python3.11/site-packages/pytensor/link/utils.py", line 738, in fgraph_to_python compiled_func = op_conversion_fn( ^^^^^^^^^^^^^^^^^ 
File "/users/igrahek/.conda/envs/pyHSSM/lib/python3.11/functools.py", line 909, in wrapper return dispatch(args[0].__class__)(*args, **kw) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ 
File "/users/igrahek/.conda/envs/pyHSSM/lib/python3.11/site-packages/pytensor/link/jax/dispatch/elemwise.py", line 12, in jax_funcify_Elemwise return jax_funcify(scalar_op, **kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ 
File "/users/igrahek/.conda/envs/pyHSSM/lib/python3.11/functools.py", line 909, in wrapper return dispatch(args[0].__class__)(*args, **kw) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ 
File "/users/igrahek/.conda/envs/pyHSSM/lib/python3.11/site-packages/pytensor/link/jax/dispatch/scalar.py", line 69, in jax_funcify_ScalarOp jax_variadic_func = getattr(jnp, op.nfunc_variadic) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ 
File "/users/igrahek/.conda/envs/pyHSSM/lib/python3.11/site-packages/jax/_src/deprecations.py", line 53, in getattr raise AttributeError(f"module {module!r} has no attribute {name!r}")AttributeError: module 'jax.numpy' has no attribute 'product'

```

**Comment by igrahek** [comment]
Thanks for the quick response Paul! This solves the issue.
