### ISSUE TITLE
Failed to converge for race model with regression

### ISSUE THREAD

**Issue by hyang336** [lnccbrown/HSSM#299]
**Describe the bug**
attempted parameter recovery with the race_no_bias_angle_4 model, with 2 independent covariates for each of the v's. The model does not seem to converge after a long chain (5000 burn-in, 10000 samples). I tried shorter chains as well, starting  from 2000 burn-in and 2000 sample. The recovery does not seem to improve with longer chains.

**HSSM version**
0.1.5

**To Reproduce**
```
from ssms.basic_simulators import simulator
import numpy as np
import pandas as pd
from scipy.special import softmax
from scipy.special import beta
import hssm
import bambi as bmb
import arviz as az
from matplotlib import pyplot as plt

outdir=YOUR_DIR_HERE

#generative params
a0=0.4
b0=1
intercept0=np.log(1/beta(a0,b0))
a1=1.5
b1=3
intercept1=np.log(1/beta(a1,b1))
a2=3
b2=1.5
intercept2=np.log(1/beta(a2,b2))
a3=1
b3=0.4
intercept3=np.log(1/beta(a3,b3))
simneural = np.random.uniform(0, 1, size=1000)#some fake neural data
simneural2= np.random.uniform(0, 1, size=1000)

#simulate simple linear relationship with 2 independent IVs
v0=intercept0 + (a0-1)*simneural + (b0-1)*(simneural2)
v1=intercept1 + (a1-1)*simneural + (b1-1)*(simneural2)
v2=intercept2 + (a2-1)*simneural + (b2-1)*(simneural2)
v3=intercept3 + (a3-1)*simneural + (b3-1)*(simneural2)

#generate trial-wise parameters with fixed a, z, and t, and bnoundary_param (in that order), assumed to take the form theta in radian
true_values = np.column_stack(
    [v0,v1,v2,v3, np.repeat([[1.5, 0.0, 0.5,0.1]], axis=0, repeats=1000)]
)

race4_v = simulator.simulator(true_values, model="race_no_bias_angle_4", n_samples=1)

dataset_race4_v = pd.DataFrame(
    {
        "rt": race4_v["rts"].flatten(),
        "response": race4_v["choices"].flatten(),
        "x": simneural,
        "y": simneural2
    }
)


#estimate parameters based on data
model_race4_v = hssm.HSSM(
    data=dataset_race4_v,
    model='race_no_bias_angle_4',
    include=[
        {
            "name": "v0",
            "prior":{"name": "Uniform", "lower": -12, "upper": 12},
            "formula": "v0 ~ 1 + x + y",
            "link": "identity",
        },
        {
            "name": "v1",
            "prior":{"name": "Uniform", "lower": -12, "upper": 12},
            "formula": "v1 ~ 1 + x + y",
            "link": "identity",
        },
        {
            "name": "v2",
            "prior":{"name": "Uniform", "lower": -12, "upper": 12},
            "formula": "v2 ~ 1 + x + y",
            "link": "identity",
        },
        {
            "name": "v3",
            "prior":{"name": "Uniform", "lower": -12, "upper": 12},
            "formula": "v3 ~ 1 + x + y",
            "link": "identity",
        }
    ],
)

#sample from the model, 2000-5000 is not enough for the chain the converge
infer_data_race4_v = model_race4_v.sample(
    sampler="nuts_numpyro", chains=2, cores=None, draws=5000, tune=10000
)

#save model
az.to_netcdf(infer_data_race4_v,outdir+'sample5000_10000_trace_simpleIND.nc4')

#diagnostic plots
az.plot_trace(
    infer_data_race4_v,
    var_names="~log_likelihood",  # we exclude the log_likelihood traces here
)
plt.savefig(outdir+'posterior_diagnostic5000_10000_simpleIND.png')

#fit summary
res_sum=az.summary(model_race4_v.traces)
res_sum.to_csv(outdir+'summary5000_10000_simpleIND.csv')
```

**Screenshots**
![posterior_diagnostic5000_10000_simpleIND](https://github.com/lnccbrown/HSSM/assets/26169163/d27fb2ee-b5fc-48fb-9a61-0cfa97dc9f4e)

**Additional context**
Add any other context about the problem here, such as the print out of the model.

**Comment by hyang336** [comment]
I have since had some new idea. Initially I thought that the poor performance might be due to parameter v's in my simulation falling outside of the bounds specified at https://github.com/lnccbrown/HSSM/blob/afa2abac8b6c3a5f19d292337096d7c372f4f49e/docs/api/defaults.md?plain=1#L123

So I modified the generative code to make sure that all v's fall inside 0 to 2.5:
```
a0=0.4
b0=1

a1=1
b1=1

a2=0.5
b2=1.5

a3=1.5
b3=0.4

simneural = np.random.uniform(0, 1, size=1000)#some fake neural data
simneural2= np.random.uniform(0, 1, size=1000)
#simulate simple linear relationship with 2 independent IVs
v0=0.5 + a0*simneural + b0*simneural2
v1=0.2 + a1*simneural + b1*simneural2
v2=0.3 + a2*simneural + b2*simneural2
v3=0.4 + a3*simneural + b3*simneural2
```

But the parameter recovery is still way off:
From v0 to v3, ground truth (intercept, a, b)______estimated (intercept, a, b)
0.5, 0.4, 1______-2.36, -1.13, 4.63
0.2, 1, 1______0.56, -0.53, 0.69
0.3, 0.5, 1.5______1.75, -0.83, -0.46
0.4, 1.5, 0.4______0.85, -0.65, 0.50

**Comment by AlexanderFengler** [comment]
These models are actually quite hard to identify, as per my own experiments.
One things that makes it complicated is that you usually get a pretty severe tradeoff between the `a` and `v` parameters. 

Try fixing `a` to a given value and potentially generate a bit more data. 

You are right that it is important that all simulated `v's` are within the training bounds specified in the `model_config` dictionary. 

Moreover, it is good to try a simple slice sampler (try passing the argument `step=pm.Slice(my_model)` to the `.sample()` function when setting `sampler = 'mcmc'`). This sampler is more robust than the `nuts_numpyro` sampler, albeit less efficient. 

Let us know if this helped :).

**Comment by hyang336** [comment]
what does "pm" stand for? My code looks like this:
```
infer_data_race4_v = model_race4_v.sample(
    step=pm.Slice(model_race4_v), sampler="mcmc", chains=1, cores=None, draws=5000, tune=10000
)
```
And it returned 
```
NameError: name 'pm' is not defined. Did you mean: 'pd'?
```

**Comment by frankmj** [comment]
Just add “import pymc as pm” earlier in the code

**Comment by hyang336** [comment]
Now it says:
```
Traceback (most recent call last):
  File "/home/hyang336/HSSM_race5_dev/HY_dev/race_4_LAN/simdata_gen_simple.py", line 104, in <module>
    step=pm.Slice(model_race4_v), sampler="mcmc", chains=1, cores=None, draws=5000, tune=10000
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hyang336/HSSM_race5_dev/HSSM_race5_dev_ENV/lib/python3.11/site-packages/pymc/step_methods/compound.py", line 116, in __new__
    model = modelcontext(kwargs.get("model"))
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hyang336/HSSM_race5_dev/HSSM_race5_dev_ENV/lib/python3.11/site-packages/pymc/model.py", line 236, in modelcontext
    raise TypeError("No model on context stack.")
TypeError: No model on context stack.
```
is "my_model" not the one I defined using hssm.HSSM?

**Comment by digicosmos86** [comment]
The argument `step` needs to be `pm.Slice(model_race4_v.pymc_model)`. This is slightly weird syntax but a requirement of PyMC to get the slice sampler to work

**Comment by hyang336** [comment]
It still returns the same error:
```
Traceback (most recent call last):
  File "/home/hyang336/HSSM_race5_dev/HY_dev/race_4_LAN/simdata_gen_simple.py", line 104, in <module>
    step=pm.Slice(model_race4_v.pymc_model), sampler="mcmc", chains=1, cores=None, draws=5000, tune=10000
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hyang336/HSSM_race5_dev/HSSM_race5_dev_ENV/lib/python3.11/site-packages/pymc/step_methods/compound.py", line 116, in __new__
    model = modelcontext(kwargs.get("model"))
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hyang336/HSSM_race5_dev/HSSM_race5_dev_ENV/lib/python3.11/site-packages/pymc/model.py", line 236, in modelcontext
    raise TypeError("No model on context stack.")
TypeError: No model on context stack.
```

**Comment by digicosmos86** [comment]
Oops... Sorry. It should be `step=pm.Slice(model=model_race4_v.pymc_model)`

**Comment by hyang336** [comment]
That worked! Fix "a" and switch to slice sampler resulted in much better parameter recovery, and the sampling was done much faster than the NUTS sampler for the same chain length. I will need to do more testing with some more complex models, but I think this can be closed for now.
