### ISSUE TITLE
TypeError: cannot pickle 'PyCapsule' object when adding intercept

### ISSUE THREAD

**Issue by Cumol** [lnccbrown/HSSM#301]
**Describe the bug**

**HSSM version**
0.1.5  with python 3.9 and latest dev version with python 3.10

**To Reproduce**
```

import hssm

cav_data = hssm.load_data("cavanagh_theta")

```
The following produces an error:

```

model_side = hssm.HSSM(
    data=cav_data,
    model="ddm",
    a = 1,
    hierarchical = False,
    include=[
	{
	    "name": "v",  # Drift rate
	    "prior": {
                "Intercept": {
		    "name": "Normal",
		    "sigma": 1,
		    "mu": 0.0,
                }
	    },
	    "formula": "v ~ 1 + (stim|subj_idx) + (1|subj_idx) + C(dbs):C(conf)",
	    "link": "identity",
	},
	{
	    "name": "z",  # Starting point
	    "prior": {
                "Intercept": {
		    "name": "Normal",
		    "sigma": 1,
		    "mu": 0.0,
                }
	    },
	    "formula": "z ~ 1 + (stim|subj_idx) + (1|subj_idx) + C(dbs):C(conf)",
	    "link": "identity",
	},
	{
	    "name": "t",  # Starting point
	    "prior": {
                "Intercept": {
		    "name": "Normal",
		    "sigma": 1,
		    "mu": 0.0,
                } 
	    },
	    "formula": "t ~ 1 + (stim|subj_idx) + (1|subj_idx) + C(dbs):C(conf)",
	    "link": "identity",
	},
    ],
)

```

```
/home/muad/anaconda3/envs/hssm10/lib/python3.10/site-packages/formulae/terms/call.py:108: FutureWarning: is_categorical_dtype is deprecated and will be removed in a future version. Use isinstance(dtype, CategoricalDtype) instead
  elif is_string_dtype(x) or is_categorical_dtype(x) or isinstance(x, CategoricalBox):
/home/muad/anaconda3/envs/hssm10/lib/python3.10/site-packages/formulae/terms/call.py:108: FutureWarning: is_categorical_dtype is deprecated and will be removed in a future version. Use isinstance(dtype, CategoricalDtype) instead
  elif is_string_dtype(x) or is_categorical_dtype(x) or isinstance(x, CategoricalBox):
Traceback (most recent call last):
  File "<string>", line 17, in __PYTHON_EL_eval
  File "<string>", line 160, in <module>
  File "/home/muad/anaconda3/envs/hssm10/lib/python3.10/site-packages/hssm/hssm.py", line 268, in __init__
    self.model = bmb.Model(
  File "/home/muad/anaconda3/envs/hssm10/lib/python3.10/site-packages/bambi/models.py", line 160, in __init__
    design = fm.design_matrices(
  File "/home/muad/anaconda3/envs/hssm10/lib/python3.10/site-packages/formulae/matrices.py", line 556, in design_matrices
    design = DesignMatrices(description, data, env)
  File "/home/muad/anaconda3/envs/hssm10/lib/python3.10/site-packages/formulae/matrices.py", line 54, in __init__
    self.model.eval(data, env)
  File "/home/muad/anaconda3/envs/hssm10/lib/python3.10/site-packages/formulae/terms/terms.py", line 1258, in eval
    self.add_extra_terms(encodings, data, env)
  File "/home/muad/anaconda3/envs/hssm10/lib/python3.10/site-packages/formulae/terms/terms.py", line 1240, in add_extra_terms
    extra_term = create_extra_term(term, subencoding, data, env)
  File "/home/muad/anaconda3/envs/hssm10/lib/python3.10/site-packages/formulae/terms/terms.py", line 1294, in create_extra_term
    extra_term = Term(*deepcopy(components))
  File "/home/muad/anaconda3/envs/hssm10/lib/python3.10/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/home/muad/anaconda3/envs/hssm10/lib/python3.10/copy.py", line 206, in _deepcopy_list
    append(deepcopy(a, memo))
  File "/home/muad/anaconda3/envs/hssm10/lib/python3.10/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/home/muad/anaconda3/envs/hssm10/lib/python3.10/copy.py", line 271, in _reconstruct
    state = deepcopy(state, memo)
  File "/home/muad/anaconda3/envs/hssm10/lib/python3.10/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/home/muad/anaconda3/envs/hssm10/lib/python3.10/copy.py", line 231, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/home/muad/anaconda3/envs/hssm10/lib/python3.10/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/home/muad/anaconda3/envs/hssm10/lib/python3.10/copy.py", line 271, in _reconstruct
    state = deepcopy(state, memo)
  File "/home/muad/anaconda3/envs/hssm10/lib/python3.10/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/home/muad/anaconda3/envs/hssm10/lib/python3.10/copy.py", line 231, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/home/muad/anaconda3/envs/hssm10/lib/python3.10/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/home/muad/anaconda3/envs/hssm10/lib/python3.10/copy.py", line 206, in _deepcopy_list
    append(deepcopy(a, memo))
  File "/home/muad/anaconda3/envs/hssm10/lib/python3.10/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/home/muad/anaconda3/envs/hssm10/lib/python3.10/copy.py", line 231, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/home/muad/anaconda3/envs/hssm10/lib/python3.10/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/home/muad/anaconda3/envs/hssm10/lib/python3.10/copy.py", line 231, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/home/muad/anaconda3/envs/hssm10/lib/python3.10/copy.py", line 161, in deepcopy
    rv = reductor(4)
TypeError: cannot pickle 'PyCapsule' object
```

But if I remove the intercept, no error, only the usual warnings about categorical predictors:
```

model_side = hssm.HSSM(
    data=cav_data,
    model="ddm",
    a = 1,
    hierarchical = False,
    include=[
	{
	    "name": "v",  # Drift rate
	    "prior": {
		    "name": "Normal",
		    "sigma": 1,
		    "mu": 0.0,
	    },
	    "formula": "v ~ 0 + (stim|subj_idx) + (1|subj_idx) + C(dbs):C(conf)",
	    "link": "identity",
	},
	{
	    "name": "z",  # Starting point
	    "prior": {
		    "name": "Normal",
		    "sigma": 1,
		    "mu": 0.0,
	    },
	    "formula": "z ~ 0 + (stim|subj_idx) + (1|subj_idx) + C(dbs):C(conf)",
	    "link": "identity",
	},
	{
	    "name": "t",  # Starting point
	    "prior": {
		    "name": "Normal",
		    "sigma": 1,
		    "mu": 0.0,
	    },
	    "formula": "t ~ 0 + (stim|subj_idx) + (1|subj_idx) + C(dbs):C(conf)",
	    "link": "identity",
	},
    ],
)

```
```

/home/muad/anaconda3/envs/hssm10/lib/python3.10/site-packages/formulae/terms/call.py:108: FutureWarning: is_categorical_dtype is deprecated and will be removed in a future version. Use isinstance(dtype, CategoricalDtype) instead
  elif is_string_dtype(x) or is_categorical_dtype(x) or isinstance(x, CategoricalBox):
/home/muad/anaconda3/envs/hssm10/lib/python3.10/site-packages/formulae/terms/call.py:108: FutureWarning: is_categorical_dtype is deprecated and will be removed in a future version. Use isinstance(dtype, CategoricalDtype) instead
  elif is_string_dtype(x) or is_categorical_dtype(x) or isinstance(x, CategoricalBox):
/home/muad/anaconda3/envs/hssm10/lib/python3.10/site-packages/formulae/terms/call.py:108: FutureWarning: is_categorical_dtype is deprecated and will be removed in a future version. Use isinstance(dtype, CategoricalDtype) instead
  elif is_string_dtype(x) or is_categorical_dtype(x) or isinstance(x, CategoricalBox):
/home/muad/anaconda3/envs/hssm10/lib/python3.10/site-packages/formulae/terms/call.py:108: FutureWarning: is_categorical_dtype is deprecated and will be removed in a future version. Use isinstance(dtype, CategoricalDtype) instead
  elif is_string_dtype(x) or is_categorical_dtype(x) or isinstance(x, CategoricalBox):
/home/muad/anaconda3/envs/hssm10/lib/python3.10/site-packages/formulae/terms/call.py:108: FutureWarning: is_categorical_dtype is deprecated and will be removed in a future version. Use isinstance(dtype, CategoricalDtype) instead
  elif is_string_dtype(x) or is_categorical_dtype(x) or isinstance(x, CategoricalBox):
/home/muad/anaconda3/envs/hssm10/lib/python3.10/site-packages/formulae/terms/call.py:108: FutureWarning: is_categorical_dtype is deprecated and will be removed in a future version. Use isinstance(dtype, CategoricalDtype) instead
  elif is_string_dtype(x) or is_categorical_dtype(x) or isinstance(x, CategoricalBox):
```

edit: removed the intercept prior in the second model (without the intercept), even though it didnt make a difference

**Comment by Cumol** [comment]
It seems to be connected to the interaction term. When I remove it, there are no errors:

```

model_side = hssm.HSSM(
    data=cav_data,
    model="ddm",
    a = 1,
    hierarchical = False,
    include=[
	{
	    "name": "v",  # Drift rate
	    "prior": {
		    "name": "Normal",
		    "sigma": 1,
		    "mu": 0.0,
	    },
	    "formula": "v ~ 1 + (stim|subj_idx) + (1|subj_idx)",
	    "link": "identity",
	},
	{
	    "name": "z",  # Starting point
	    "prior": {
		    "name": "Normal",
		    "sigma": 1,
		    "mu": 0.0,
	    },
	    "formula": "z ~ 1 + (stim|subj_idx) + (1|subj_idx)",
	    "link": "identity",
	},
	{
	    "name": "t",  # Starting point
	    "prior": {
		    "name": "Normal",
		    "sigma": 1,
		    "mu": 0.0,
	    },
	    "formula": "t ~ 1 + (stim|subj_idx) + (1|subj_idx)",
	    "link": "identity",
	},
    ],
)
```

**Comment by Cumol** [comment]
```
model_side = hssm.HSSM(
    data=cav_data,
    model="ddm",
    a = 1,
    hierarchical = False,
    include=[
	{
	    "name": "v",  # Drift rate
	    "prior": {
		    "name": "Normal",
		    "sigma": 1,
		    "mu": 0.0,
	    },
	    "formula": "v ~ 1 + C(dbs)*C(conf)",
	    "link": "identity",
	},
	{
	    "name": "z",  # Starting point
	    "prior": {
		    "name": "Normal",
		    "sigma": 1,
		    "mu": 0.0,
	    },
	    "formula": "z ~ 1 + C(dbs)*C(conf)",
	    "link": "identity",
	},
	{
	    "name": "t",  # Starting point
	    "prior": {
		    "name": "Normal",
		    "sigma": 1,
		    "mu": 0.0,
	    },
	    "formula": "t ~ 1 + C(dbs)*C(conf)",
	    "link": "identity",
	},
    ],
)

```
This however, seem to work

**Comment by digicosmos86** [comment]
Thanks for letting us know! I tested the code myself and got a different but very similar error. It seems this happens when `bambi` is trying to create design matrices. It uses `deepcopy` which involves pickling some objects, but not object types are supported. Will create an issue for `bambi` developers

**Comment by tomicapretto** [comment]
@Cumol have a look at https://github.com/bambinos/bambi/issues/738#issuecomment-1772793970 :)

**Comment by digicosmos86** [comment]
@Cumol I suppose we can close this now? Please feel free to reopen this if you have any further questions
