### ISSUE TITLE
error importing hssm

### ISSUE THREAD

**Issue by sallidina** [lnccbrown/HSSM#496]
Hi! I'm attempting to install the newest version of hssm into a new conda environment on Windows, and I'm getting the following error when I run `import hssm`. Any ideas how to fix this?

Traceback (most recent call last):
  File "__init__.cython-30.pxd", line 1024, in numpy.import_array
ImportError: DLL load failed while importing _multiarray_umath: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\allidina.1\AppData\Local\anaconda3\envs\HSSM_testing\Lib\site-packages\hssm\__init__.py", line 14, in <module>
    from .config import ModelConfig
  File "C:\Users\allidina.1\AppData\Local\anaconda3\envs\HSSM_testing\Lib\site-packages\hssm\config.py", line 10, in <module>
    from .defaults import LogLik, LoglikKind, SupportedModels, default_model_config
  File "C:\Users\allidina.1\AppData\Local\anaconda3\envs\HSSM_testing\Lib\site-packages\hssm\defaults.py", line 7, in <module>
    import bambi as bmb
  File "C:\Users\allidina.1\AppData\Local\anaconda3\envs\HSSM_testing\Lib\site-packages\bambi\__init__.py", line 3, in <module>
    from pymc import math
  File "C:\Users\allidina.1\AppData\Local\anaconda3\envs\HSSM_testing\Lib\site-packages\pymc\__init__.py", line 46, in <module>
    __set_compiler_flags()
  File "C:\Users\allidina.1\AppData\Local\anaconda3\envs\HSSM_testing\Lib\site-packages\pymc\__init__.py", line 29, in __set_compiler_flags
    import pytensor
  File "C:\Users\allidina.1\AppData\Local\anaconda3\envs\HSSM_testing\Lib\site-packages\pytensor\__init__.py", line 119, in <module>
    from pytensor import scalar, tensor
  File "C:\Users\allidina.1\AppData\Local\anaconda3\envs\HSSM_testing\Lib\site-packages\pytensor\scalar\__init__.py", line 2, in <module>
    from .math import *
  File "C:\Users\allidina.1\AppData\Local\anaconda3\envs\HSSM_testing\Lib\site-packages\pytensor\scalar\math.py", line 12, in <module>
    import scipy.special
  File "C:\Users\allidina.1\AppData\Local\anaconda3\envs\HSSM_testing\Lib\site-packages\scipy\special\__init__.py", line 777, in <module>
    from . import _ufuncs
  File "scipy\\special\\_ufuncs.pyx", line 1, in init scipy.special._ufuncs
  File "scipy\\special\\_ufuncs_extra_code_common.pxi", line 26, in init scipy.special._ufuncs_cxx
  File "__init__.cython-30.pxd", line 1026, in numpy.import_array
ImportError: numpy._core.multiarray failed to import

**Comment by digicosmos86** [comment]
Hi @sallidina,

It seems that there are some compatibility issues between PyMC, pytensor, and scipy.

Can you print the versions of these packages in your environment? You can also just print the versions of all packages in the environment

**Comment by sallidina** [comment]
Here is the list! I should mention that to install, I installed jax and then followed the instructions [here ](https://github.com/lnccbrown/HSSM/discussions/470#discussioncomment-9843407)since I was having the same issue initially.

Package             Version
------------------- --------
arviz               0.18.0
bambi               0.13.0
cachetools          5.4.0
certifi             2024.7.4
charset-normalizer  3.3.2
cloudpickle         3.0.0
colorama            0.4.6
cons                0.4.6
contourpy           1.2.1
cycler              0.12.1
dm-tree             0.1.8
etuples             0.3.9
filelock            3.15.4
fonttools           4.53.1
formulae            0.5.4
fsspec              2024.6.1
graphviz            0.20.3
h5netcdf            1.3.0
h5py                3.11.0
hddm_wfpt           0.1.4
HSSM                0.2.3
huggingface-hub     0.23.5
idna                3.7
jax                 0.4.30
jaxlib              0.4.30
joblib              1.4.2
kiwisolver          1.4.5
logical-unification 0.4.6
markdown-it-py      3.0.0
matplotlib          3.9.1
mdurl               0.1.2
miniKanren          1.0.3
mkl-service         2.4.1
ml-dtypes           0.4.0
multipledispatch    0.6.0
munkres             1.1.4
numpy               1.26.4
numpyro             0.15.1
onnx                1.16.1
opt-einsum          3.3.0
packaging           24.1
pandas              2.2.2
pillow              10.4.0
pip                 24.0
protobuf            5.27.2
psutil              6.0.0
Pygments            2.18.0
pymc                5.16.2
pyparsing           3.1.2
pytensor            2.25.2
python-dateutil     2.9.0
pytz                2024.1
PyYAML              6.0.1
requests            2.32.3
rich                13.7.1
scikit-learn        1.5.1
scipy               1.13.1
seaborn             0.13.2
setuptools          69.5.1
six                 1.16.0
ssm-simulators      0.7.2
threadpoolctl       3.5.0
toolz               0.12.1
tqdm                4.66.4
typing_extensions   4.12.2
tzdata              2024.1
urllib3             2.2.2
wheel               0.43.0
xarray              2024.6.0
xarray-einstats     0.7.0

**Comment by digicosmos86** [comment]
Hi @sallidina 

Looks like people have similar problems with numpy installation: there are a few things you can do from [this post](https://stackoverflow.com/questions/54063285/numpy-is-already-installed-with-anaconda-but-i-get-an-importerror-dll-load-fail/58194133#58194133):

1: install numpy with pip:

Just do 

```
conda remove numpy
pip install numpy==1.26.4
```

2. Add Anaconda and Python to your environment PATH.

Follow [this post](https://superuser.com/questions/1406191/getting-the-error-dll-load-failed-the-specified-module-could-not-be-found-wh). You might need to update the paths to where your Anaconda and Python are installed on your computer. Newer versions might have different defaults.

3. Some other folks have said that pip installing numpy in the base environment have worked. Might be a good idea to try,

**Comment by sallidina** [comment]
Thanks for your reply! These didn't resolve the issue for me, but I realized that I do not need to separately install jax before the pymc and hssm install. When I just install the latter two, it worked okay.

**Comment by digicosmos86** [comment]
Yeah you are right. Jax is not necessary as long as you are not using jax-based sampling. Is this issue resolved for you now?

**Comment by suraiya-a** [comment]
Yes, it works okay when I don't use jax, so it is resolved. Thanks!

**Comment by sallidina** [comment]
Yes, it works okay when I don't use jax, so it is resolved. Thanks!
